services:
  db: 
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
    container_name: db
    restart: always
    ports: 
      - 1234:5432
    env_file:
      - .env

  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env
  
volumes:
  pg: